Logging to /tmp/output436.log

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -46,4 +46,4 @@ jobs:
 
       - name: Print RPC output log
         if: always()
-        run: cat /tmp/output136.log || echo "Log file not found"
+        run: cat /tmp/output*.log || echo "Log file not found"
